### ISSUE TITLE
[FEATURE]: Add Timer to Quiz

### ISSUE THREAD

**Issue by bj-jiwrajka** [SnowScriptWinterOfCode/QuickQuiz#11]
Currently, the quiz application does not include a timer functionality. This feature request is to add a timer that counts down during the quiz, providing users with a time limit to answer each question.

### Additional Information
This feature enhances the quiz experience by adding an element of time pressure, making it more engaging for users.

@Nitya-Pasrija I would love to work on this issue, please assign it to me :)

**Comment by Nitya-Pasrija** [comment]
Woohoo! Your first ever issue with us in this repository has been created🎊🎊!!

**Comment by PranjaliBhardwaj** [comment]
I can add timer in project by using html and js, in js we will create var and use if statement. @Nitya-Pasrija . Kindly assign this issue to me.

**Comment by Garima-149** [comment]
@Nitya-Pasrija  ... I would also love to work upon it.Can i take this issue?

**Comment by Akanchha112** [comment]
Hey @PranjaliBhardwaj! you can start working on this issue. But try to do it ASAP. :)

**Comment by PranjaliBhardwaj** [comment]
Set me assignee @Akanchha112

**Comment by bj-jiwrajka** [comment]
@Akanchha112 since it was already added, I was not workin on this 

![image](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/97835955/1b2b5686-f1ca-4433-8757-15f166347b9b)

Chexk my PR #14 for reference

**Comment by Akanchha112** [comment]
> @Akanchha112 since it was already added, I was not workin on this
> 
> ![image](https://private-user-images.githubusercontent.com/97835955/293688982-1b2b5686-f1ca-4433-8757-15f166347b9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTQwMTksIm5iZiI6MTcwNDIxMzcxOSwicGF0aCI6Ii85NzgzNTk1NS8yOTM2ODg5ODItMWIyYjU2ODYtZjFjYS00NDMzLTg3NTctMTVmMTY2MzQ3YjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE2NDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OTQxMmUwOWQ0YjM0MGVhNGZjOGY5YjI5N2Y2NmRhNTZkZDJjNDhmOTA5MmU2YWM5OTRmZTBiMTNlNGRmN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aPuPyiUOcGVbm1JM3P4pVx5t-O203dJQE0B3EJ9sghw)
> 
> Chexk my PR #14 for reference

Ok. @PranjaliBhardwaj Since this issue is already resolved I am closing it.
