### ISSUE TITLE
Move Dark Mode/Light Mode Button Above

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [SnowScriptWinterOfCode/QuickQuiz#2]
## Description
The Dark Mode/Light Mode button is currently positioned below, and we need to move it above to improve user experience and accessibility.

### Context
- **Current Behavior:**
  The Dark Mode/Light Mode button is currently located below [specify the element].

- **Expected Behavior:**
  We want to relocate the Dark Mode/Light Mode button so that it appears above [specify the element].

### Screenshots 
![image](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/94298791/fb4d0e3b-c87c-4038-a488-79509cd5d083)

### Additional Information
Ensure that the button's new position is visually appealing and does not conflict with other elements on the page.

**Comment by Nitya-Pasrija** [comment]
Woohoo! Your first ever issue with us in this repository has been created🎊🎊!!

**Comment by vanshita007** [comment]
I would really like to work upon it 
Please assign this to me..

**Comment by i-am-SnehaChauhan** [comment]
Hey @vanshita007, I am assigning this issue to u you have two days to complete it then i have to assign to someone else.

**Comment by vanshita007** [comment]
> Hey @vanshita007, I am assigning this issue to u you have two days to complete it then i have to assign to someone else.

Thanks for assigning me this issue ..
Issue is resolved!!

**Comment by PranjaliBhardwaj** [comment]
Hey @i-am-SnehaChauhan  I would like to work on this issue, I think I can solve this problem by simply changing margins of button. I have experience in CSS  so kindly allow me to resolve this issue.

**Comment by i-am-SnehaChauhan** [comment]
Hey @vanshita007, If you are unable to complete this task within the given time, I will have to assign it to @PranjaliBhardwaj. Thank you.
