### ISSUE TITLE
Want to  show correct answer to participant  and mark question numbers 

### ISSUE THREAD

**Issue by Garima-149** [SnowScriptWinterOfCode/QuickQuiz#20]

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by Garima-149** [comment]
In case ,answer is wrong .Then also for better user interaction .It should have correct answer too to show beneath the question. @Nitya-Pasrija  Please assign this work to me

**Comment by Garima-149** [comment]
May i start working upon it ? @Nitya-Pasrija 
@i-am-SnehaChauhan

**Comment by Akanchha112** [comment]
@Garima-149  you can start working on it.

**Comment by Garima-149** [comment]
![Screenshot (3)](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/143211271/cebcf60c-c8f0-4054-a6e7-866464f34690)
I marked question numbers at each question.Please review it. @Akanchha112 @Nitya-Pasrija

**Comment by Garima-149** [comment]
![Screenshot (5)](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/143211271/f997f0a2-8ddf-4e4c-956d-14150468e697)
@Nitya-Pasrija @Akanchha112 Please review it .Can i replace these options with numbers ?or Can you please guide if in any way I could show A or B instead of numbers as correct option?

**Comment by Garima-149** [comment]
![Screenshot (6)](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/143211271/d9bd8edb-b1c5-467b-bb27-26a48eb25920)
@Akanchha112 I changed the numbers with options .please review it .Do i make a pull request now?

**Comment by Nitya-Pasrija** [comment]
Go for it :)

**Comment by Garima-149** [comment]
![Screenshot (8)](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/143211271/2af07ad0-9ebd-4e99-a27b-ca22f09e8e90)
@Akanchha112 @Nitya-Pasrija @i-am-SnehaChauhan  This is the problem I am getting when clicking on commit changes option.Please guide me How can I resolve this?

**Comment by Garima-149** [comment]
@Nitya-Pasrija 
![Screenshot (9)](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/143211271/4bb09519-d9d3-4806-97b3-94a699bf9362)
I gave username and user id .But it is still not committing changes I made.Please tell the next step I should go ?

**Comment by Garima-149** [comment]
I created pr .Please check @Nitya-Pasrija
