### ISSUE TITLE
Adding hover effects on the buttons

### ISSUE THREAD

**Issue by MonalikaPatnaik** [SnowScriptWinterOfCode/QuickQuiz#24]
I want to add hover effects to the buttons in the landing page

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by Anushreebasics** [comment]
@i-am-SnehaChauhan please assign this issue to me

**Comment by Akanchha112** [comment]
@MonalikaPatnaik issue is assigned to you. If, in any case, you don't want to work on it drop a message, issue will be reassigned to anushreebasics.
