### ISSUE TITLE
add social media sharing functionality to allow users to share their quiz results.

### ISSUE THREAD

**Issue by Anushreebasics** [SnowScriptWinterOfCode/QuickQuiz#27]

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by bj-jiwrajka** [comment]
@Nitya-Pasrija  @Akanchha112 you can assign me

**Comment by Anushreebasics** [comment]
@Akanchha112 assign it to me

**Comment by Akanchha112** [comment]
@bj-jiwrajka  and @Anushreebasics what about it that you guys try to work on it together and help each other? Otherwise, I have to assign it to any one of you.

**Comment by bj-jiwrajka** [comment]
> @bj-jiwrajka and @Anushreebasics what about it that you guys try to work on it together and help each other? Otherwise, I have to assign it to any one of you.

cool, you can assign it to @Anushreebasics , if needed I'll be happy to help :)
