### ISSUE TITLE
Making the text look good

### ISSUE THREAD

**Issue by MonalikaPatnaik** [SnowScriptWinterOfCode/QuickQuiz#31]
Currently the text "High Scores" doesn't look good and lacks design. I want to align the text to center and change its text size. Kindly assign this issue to me!
![image](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/99353300/a2ac636a-9ac5-45fe-9a63-7584ff259ad5)

**Comment by Akanchha112** [comment]
Hey @MonalikaPatnaik! There is a major merge in the repository so kindly check it once again and see if the issue still exists there then we can assign it to you.

**Comment by MonalikaPatnaik** [comment]
Hi @Akanchha112, yes the issue is still there..I want to change the font size, it's not looking good to me
![image](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/99353300/2a719ba9-b8c1-4735-a5bf-d6432c5cd957)
