### ISSUE TITLE
[UI] Add Animation to timer when less than 5 seconds are remaining.

### ISSUE THREAD

**Issue by Akanchha112** [SnowScriptWinterOfCode/QuickQuiz#37]
[UI] Add Animation to the timer when less than 5 seconds are remaining.

DESC: Make timer integer bounce something like as shown below in gif (of 24hrs)

[<iframe src="https://giphy.com/embed/88fKfoAcRCSHPuEbdd" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/crowdfunding-crowdfunder-crowdfunderuk-88fKfoAcRCSHPuEbdd">via GIPHY</a></p>](https://giphy.com/gifs/crowdfunding-crowdfunder-crowdfunderuk-88fKfoAcRCSHPuEbdd)

![image](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/100962900/061c668f-bfc6-42b7-bbac-125085263522)

**Comment by bj-jiwrajka** [comment]
@Akanchha112 I'll work on it
