### ISSUE TITLE
Update Scoring System Based on Response Time Interval

### ISSUE THREAD

**Issue by avanimathur** [SnowScriptWinterOfCode/QuickQuiz#52]
The scoring system will now allocate 10 points if the answer is submitted within the initial 5 seconds, 5 points if provided between 5 to 10 seconds, and 2 points if the response falls within the last 10 to 15 seconds timeframe.

Please assign it to me. @Nitya-Pasrija @Akanchha112 @i-am-SnehaChauhan

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.
