### ISSUE TITLE
Bug: Responsiveness of Audio button

### ISSUE THREAD

**Issue by MonalikaPatnaik** [SnowScriptWinterOfCode/QuickQuiz#58]
The audio button is going out of the screen for smaller screen sizes. I want to make it responsive for smaller screens
![image](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/99353300/3594bca2-b2c0-4cd0-9d0a-104fb0b0c482)

**Comment by PranjaliBhardwaj** [comment]
I can make it responsive by css commands , @media and view port meta tag. @Nitya-Pasrija @i-am-SnehaChauhan
