### ISSUE TITLE
Display of Score on The Screen

### ISSUE THREAD

**Issue by avanimathur** [SnowScriptWinterOfCode/QuickQuiz#59]
Showcase a +10 increment on the screen (with an animation effect) when the correct answer is given by the user.

![Screenshot (83)](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/151984867/2350d0ea-46cc-4b3e-bb56-46d016825da1)

Please assign it to me @Nitya-Pasrija @i-am-SnehaChauhan [@Akanchha112](https://github.com/Akanchha112)

**Comment by Akanchha112** [comment]
Hey!! I will assign this issue to you but these scores are decreasing according to the time left so make sure you go through this functionality and show the score as it is decreasing.
