### ISSUE TITLE
Adding Rules To The Quiz

### ISSUE THREAD

**Issue by avanimathur** [SnowScriptWinterOfCode/QuickQuiz#60]
We  may include a 'Rules' button in the Quiz, providing users with guidelines on how to play the game.
It would appear something like this - 

![Screenshot (88)](https://github.com/SnowScriptWinterOfCode/QuickQuiz/assets/151984867/5124b339-9d77-4e86-973d-0e72f25b72bd)

I would like to add this feature in both the Light and Dark modes.

Please assign it to me @Nitya-Pasrija @i-am-SnehaChauhan [@Akanchha112](https://github.com/Akanchha112)

**Comment by Akanchha112** [comment]
Hey!! Make sure to go through the website once more to make everything clear. In Questions, the less time we take, higher the score we will get.
