### ISSUE TITLE
[BUG]: Audio button not working

### ISSUE THREAD

**Issue by hars-21** [SnowScriptWinterOfCode/QuickQuiz#61]
The Speaker/Mute button is not working. It is also not perfectly aligned with the page.

Fix: align the button with the page.
make button funtionable.
change speaker state to mute and vice-versa.
visible on all pages.

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by hars-21** [comment]
Please assign this issue to me.
